// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Area {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  kind?: "area" | "lifestyle";
  tagline?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  intro?: PortableTextBlock[];
  highlights?: unknown;
  listings_heading?: string;
  listings_source?: "featured" | "newest" | "handpicked";
  listings_slugs?: string;
  listings_sale_or_rental?: "sale" | "rental";
  listings_property_type?: string;
  listings_limit?: number;
  body?: PortableTextBlock[];
  show_testimonials?: boolean;
  faqs?: unknown;
  cta_heading?: string;
  cta_text?: string;
  cta_label?: string;
  cta_href?: string;
  seo_title?: string;
  seo_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  featured_section_heading?: string;
  featured_collection_mode?: "split_featured" | "featured_any" | "newest_any" | "newest_sale" | "newest_rental" | "property_type_any" | "property_type_sale" | "property_type_rental";
  featured_item_limit?: number;
  featured_property_type?: string;
  pre_featured_content?: PortableTextBlock[];
  post_featured_content?: PortableTextBlock[];
  trust_content?: PortableTextBlock[];
  faqs?: unknown;
  seo_title?: string;
  seo_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  excerpt?: string;
  author?: string;
  key_takeaways?: unknown;
  seo_title?: string;
  seo_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Team {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  title?: string;
  bio?: PortableTextBlock[];
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  email?: string;
  phone?: string;
  speciality?: string;
  languages?: string;
  social_links?: unknown;
  display_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role?: string;
  quote: string;
  rating?: number;
  property_slug?: string;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    areas: Area;
    pages: Page;
    posts: Post;
    team: Team;
    testimonials: Testimonial;
  }
}